config/routes.rb
Rails.application.routes.draw do
  get 'gji/getjobindex' , as: 'getjobindex'
  get 'gjd/getjobdetails' , as: 'getjobdetails'

  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gjd_controller.rb
class GjdController < ApplicationController
  def getjobdetails
    if params[:jobid]
      require "net/http"
      require "uri"
      uri = URI.parse("https://jobs.apple.com/us/requisition/detail.json")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      request = Net::HTTP::Post.new(uri.request_uri)
      request.body = "requisitionId=#{params[:jobid]}&reqType=REQ&clientOffset=-300"
      request["Content-Type"] = "application/x-www-form-urlencoded"
      puts "#{request.body}"
      response = http.request(request)
      @response = response.body
    end
  end
end

app/controllers/gji_controller.rb
class GjiController < ApplicationController
  def getjobindex
    if params[:jobid]
      require "net/http"
      require "uri"
      uri = URI.parse("https://jobs.apple.com/us/search/search-result")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE

      request = Net::HTTP::Post.new(uri.request_uri)
      request.body = "searchRequestJson=#{
      {
        :searchString => '', :jobType => 0, :sortBy => 'req_open_dt', :sortOrder => '1', :language => nil, :autocomplete => nil, :delta => 0, :numberOfResults => 0, :pageNumber => 0, :internalExternalIndicator => 0, :lastRunDate => 0, :countryLang => nil,
      :filters =>
      {
        :locations =>
        {
          :location =>
          [{
            :type => 0, :code => 'USA', :countryCode => nil, :cityCode => nil, :cityName =>nil
            }]
          },
          :languageSkills => nil, :jobFunctions => nil, :retailJobSpecs => nil, :businessLine => nil, :hiringManagerId => nil
        },
            :requisitionIds => nil
          }.to_json
          }
          &clientOffset=-300"

      request["Content-Type"] = "application/x-www-form-urlencoded"
      response = http.request(request)
      #
      # if response.message == "Not Found" && retry_counter < 3
      #   retry_counter += 1
      #   response3 = http3.request(request3)
      #   puts "#{gjrd}"
      #   puts "#{response3.message}"
      # elsif response3.message =="ok"
      #   retry_counter = 0
      # elsif retry_counter = 3
      #   retry_counter = 0
      # end
      puts "#{response.message}"
      @gjiresponse = response.body
      @gjirequest = request.body

      @doc = Nokogiri::XML("#{@gjiresponse}")

      @reqs = @doc.xpath("//requisition")
      @retail_job_id_list = @reqs.map do |node|
        node.xpath(".//jobId").text if node.xpath(".//jobTypeCategory").text == "Retail"
      end.compact

      @corp_job_id_list = @reqs.map do |node|
        node.xpath(".//jobId").text if node.xpath(".//jobTypeCategory").text != "Retail"
      end.compact

      retry_counter = 0
      results = []
      @corp_job_id_list.each do |gjcd|
        uri = URI.parse("https://jobs.apple.com/us/requisition/detail.json")
        http2 = Net::HTTP.new(uri.host, uri.port)
        http2.use_ssl = true
        http2.verify_mode = OpenSSL::SSL::VERIFY_NONE
        request2 = Net::HTTP::Post.new(uri.request_uri)
        request2.body = "requisitionId=#{gjcd}&reqType=REQ&clientOffset=-300"
        request2["Content-Type"] = "application/x-www-form-urlencoded"
        response2 = http2.request(request2)
        puts "#{gjcd}"
        puts "#{response2.message}"
        @gjirequest = response2.body
        if response2.message == "Not Found" && retry_counter < 5
          sleep(2)
          retry_counter += 1
          response3 = http2.request(request2)
          puts "#{gjcd}"
          puts "#{response2.message}"
        elsif response2.message =="ok"
          retry_counter = 0
        elsif retry_counter = 5
          retry_counter = 0
        end
        results << JSON.parse(response2.body) if response2.body.length > 0
      end

      puts "#{@retaildetail}"
      @retail_job_id_list.each do |gjrd|
        uri = URI.parse("https://jobs.apple.com/us/requisition/retaildetail.json")
        http3 = Net::HTTP.new(uri.host, uri.port)
        http3.use_ssl = true
        http3.verify_mode = OpenSSL::SSL::VERIFY_NONE
        request3 = Net::HTTP::Post.new(uri.request_uri)
        request3.body = "requisitionId=#{gjrd}&reqType=PT&clientOffset=-300"
        request3["Content-Type"] = "application/x-www-form-urlencoded"
        response3 = http3.request(request3)
        puts "#{gjrd}"
        puts "#{response3.message}"
        @gjirequest = response3.body
        if response3.message == "Not Found" && retry_counter < 3
          sleep(1)
          retry_counter += 1
          response3 = http3.request(request3)
          puts "#{gjrd}"
          puts "#{response3.message}"
        elsif response3.message == "ok"
          retry_counter = 0
        elsif retry_counter = 3
          retry_counter = 0
        end
        results << JSON.parse(response3.body) if response3.body.length > 0
      end
      results
      my_xml = results.to_xml(root: :Jobs)
      puts "#{results}"
      File.open("results#{Time.now.to_i}.xml",'w') do |f|
        f.puts my_xml
      end
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :jobid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gjd_helper.rb
module GjdHelper
end

app/helpers/gji_helper.rb
module GjiHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/gjd/getjobdetails.html.erb
<%= "#{@response}" %>

app/views/gji/getjobindex.html.erb
<h1>Gji</h1>
<p>
  <%= "#{@gjirequest}" %>
  </p>
  <p>
    <%= "#{@gjiresponse}" %>
    </p>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :jobid %><br>
    <%= f.text_field :jobid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Jobid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= job.jobid %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Jobid:</strong>
  <%= @job.jobid %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ajf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>